//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmnesiaPicasso.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmnesiaPicasso.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;&lt;/author&gt;
        ///      &lt;authoring_tool&gt;Amnesia Picasso&lt;/authoring_tool&gt;
        ///      &lt;comments&gt;&lt;/comments&gt;
        ///      &lt;source_data&gt;&lt;/source_data&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;created&gt;2009-04-23T09:29:04Z&lt;/created&gt;
        ///    &lt;modified&gt;2009-04-23T09:29:04Z&lt;/modified&gt;
        ///    &lt;unit meter=&quot;1.0&quot; name=&quot;meter&quot;/&gt;
        ///    &lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///  &lt;/asset&gt;
        ///  &lt;library_physics_scenes&gt;
        ///    &lt;physics_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string painting_diego_dae {
            get {
                return ResourceManager.GetString("painting_diego_dae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Entity&gt;
        ///    &lt;EditorSession&gt;
        ///        &lt;ViewportConfig SelectedViewport=&quot;0&quot; UsingEnlargedViewport=&quot;false&quot;&gt;
        ///            &lt;Viewport CameraPosition=&quot;0.045000 0.890000 20.000000&quot; CameraTarget=&quot;0.045000 0.890000 0.000000&quot; CameraZoom=&quot;2.600000&quot; Preset=&quot;0&quot; RenderMode=&quot;1&quot; ShowGrid=&quot;true&quot; /&gt;
        ///            &lt;Viewport CameraPosition=&quot;20.000000 0.000000 0.000000&quot; CameraTarget=&quot;0.000000 0.000000 0.000000&quot; CameraZoom=&quot;0.000000&quot; Preset=&quot;1&quot; RenderMode=&quot;1&quot; ShowGrid=&quot;true&quot; /&gt;
        ///            &lt;Viewport CameraPosition=&quot;0.000000 20. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string painting_diego_ent {
            get {
                return ResourceManager.GetString("painting_diego_ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Material&gt;
        ///    &lt;Main DepthTest=&quot;True&quot; HeightMapScale=&quot;0.05&quot; PhysicsMaterial=&quot;Default&quot; Type=&quot;SolidDiffuse&quot; /&gt;
        ///    &lt;TextureUnits&gt;
        ///        &lt;Diffuse AnimFrameTime=&quot;&quot; AnimMode=&quot;&quot; File=&quot;dead_painting.tga&quot; Mipmaps=&quot;true&quot; Type=&quot;2D&quot; Wrap=&quot;Repeat&quot; /&gt;
        ///    &lt;/TextureUnits&gt;
        ///&lt;/Material&gt;
        ///.
        /// </summary>
        internal static string painting_diego_mat {
            get {
                return ResourceManager.GetString("painting_diego_mat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap painting_diego_template {
            get {
                object obj = ResourceManager.GetObject("painting_diego_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
